
default: &default
  adapter: postgresql
  encoding: unicode

  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: health_checker
  username: health_checker_user
  password: D6AS0Qs5i9pHkz4OwBraUCgy1kNYOOvF


development:
  <<: *default
  database: myapp_development
 
test:
  <<: *default
  database: myapp_test

production:
  primary: &primary_production
    <<: *default
    database: myapp_production
    username: myapp
    password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: myapp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: myapp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: myapp_production_cable
    migrations_paths: db/cable_migrate
